{
 "title": "k6 Prometheus",
 "description": "Visualize k6 OSS results stored in Prometheus",
 "tags": [
  "prometheus",
  "k6"
 ],
 "time": { "from": "2026-05-05T08:11:33.863Z", "to": "2026-05-05T08:12:41.250Z" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus DS", "query": "prometheus" },
   { "name": "testid", "label": "Test ID", "query": { "query": "label_values(k6_vus,testid)" } },
   { "name": "quantile_stat", "label": "Trend Metrics Query", "query": "min,max,avg,p90,p95,p99" },
   {
    "name": "API",
    "query": {
     "query": "label_values(k6_http_req_duration_avg{expected_response=\"false\"},api)"
    }
   },
   {
    "name": "transaction",
    "query": {
     "query": "label_values(k6_http_req_duration_avg,transaction)"
    }
   },
   { "name": "Group", "query": { "query": "label_values(group)" } },
   { "name": "adhoc_filter", "label": "AdhocFilter" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Performance Overview",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(k6_vus{testid=~\"$testid\"})",
     "legendFormat": "vus"
    },
    {
     "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_duration_$quantile_stat"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "http_req_s"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors"
    }
   ]
  },
  {
   "title": "HTTP requests Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{testid=~\"$testid\",name!=\"http://10.243.208.74:3100/loki/api/v1/push\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP request detail",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\",name!=\"http://10.243.208.74:3100/loki/api/v1/push\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"true\",name!=\"http://10.243.208.74:3100/loki/api/v1/push\"})",
     "legendFormat": "__auto"
    },
    { "expression": "$A/$C*100", "type": "math" }
   ]
  },
  {
   "title": "Peak RPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "stat",
   "description": "Select a different Stat to change the query",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checks Success Rate (aggregate individual checks)",
   "type": "stat",
   "description": "Filter by check name to query a particular check",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(round(k6_checks_rate{testid=~\"$testid\"}, 0.1)*100)",
     "legendFormat": "k6_checks_rate"
    }
   ]
  },
  {
   "title": "Peak TPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Trans/s" } },
   "targets": [
    {
     "expr": "sum(irate(k6_trx_count_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Duration",
   "type": "stat",
   "description": "Select a different Stat to change the query",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(k6_trx_duration_pass_$quantile_stat{testid=~\"$testid\"})/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Iterations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(k6_iteration_duration_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "iteration_duration_$quantile_stat"
    },
    {
     "expr": "avg(k6_dropped_iterations_total{testid=~\"$testid\"})",
     "legendFormat": "dropped_iterations"
    }
   ]
  },
  {
   "title": "Checks list",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "round(k6_checks_rate{testid=~\"$testid\"}, 0.1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(irate(k6_data_sent_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "data_sent"
    },
    {
     "expr": "avg(irate(k6_data_received_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "data_received"
    }
   ]
  },
  {
   "title": "OverAll TPS,RPS,ResponseTime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPS over all",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum(irate(k6_trx_count_total{  testid=~\"$testid\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (transaction) (irate(k6_trx_count_total{  testid=~\"$testid\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPS Over All",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "sum(irate(k6_http_reqs_total{  testid=~\"$testid\",expected_response=\"true\",name!=\"http://10.243.208.74:3100/loki/api/v1/push\",\n    transaction!=\"\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (api)(irate(k6_http_reqs_total{  testid=~\"$testid\",expected_response=\"true\",name!=\"http://10.243.208.74:3100/loki/api/v1/push\",\n    transaction!=\"\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transaction Responstime",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "avg(k6_trx_duration_$quantile_stat{testid=~\"$testid\"})/1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (transaction)(k6_trx_duration_$quantile_stat{testid=~\"$testid\"})/1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Api ResponseTime",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 95 },
     "targets": [
      {
       "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (api) (k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "TPS Channel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPS $Group",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 357 },
     "repeat": "Group",
     "targets": [
      {
       "expr": "sum(irate(k6_trx_count_total{testid=~\"$testid\",group=\"::$Group\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (transaction)(irate(k6_trx_count_total{testid=~\"$testid\",group=\"::$Group\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "RPS Channel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS $Group",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 371 },
     "repeat": "Group",
     "targets": [
      {
       "expr": "sum(irate(k6_http_reqs_total{  testid=~\"$testid\",group=\"::$Group\",expected_response=\"true\",name!=\"http://10.243.208.74:3100/loki/api/v1/push\",\n    transaction!=\"\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (api)(irate(k6_http_reqs_total{  testid=~\"$testid\",group=\"::$Group\",expected_response=\"true\",name!=\"http://10.243.208.74:3100/loki/api/v1/push\",\n    transaction!=\"\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Latency Timings",
     "type": "timeseries",
     "description": "Select a different Stat to change the query\n\n<a href=\"https://k6.io/docs/using-k6/metrics/reference/#http\" target=\"_blank\">HTTP-specific built-in metrics</a>",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 372 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(k6_http_req_blocked_$quantile_stat{testid=~\"$testid\"})",
       "legendFormat": "http_req_blocked_$quantile_stat"
      },
      {
       "expr": "avg(k6_http_req_tls_handshaking_$quantile_stat{testid=~\"$testid\"})",
       "legendFormat": "http_req_tls_handshaking_$quantile_stat"
      },
      {
       "expr": "avg(k6_http_req_sending_$quantile_stat{testid=~\"$testid\"})",
       "legendFormat": "http_req_sending_$quantile_stat"
      },
      {
       "expr": "avg(k6_http_req_waiting_$quantile_stat{testid=~\"$testid\"})",
       "legendFormat": "http_req_waiting_$quantile_stat"
      },
      {
       "expr": "avg(k6_http_req_receiving_$quantile_stat{testid=~\"$testid\"})",
       "legendFormat": "http_req_receiving_$quantile_stat"
      },
      {
       "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
       "legendFormat": "http_req_duration_$quantile_stat"
      }
     ]
    },
    {
     "title": "HTTP Latency Stats",
     "type": "timeseries",
     "description": "Select a different Stat to change the query",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 372 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
       "legendFormat": "http_req_duration_$quantile_stat"
      },
      {
       "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\", expected_response=\"true\"})",
       "legendFormat": "success_http_req_duration_$quantile_stat"
      },
      {
       "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\", expected_response=\"false\"})",
       "legendFormat": "errors_http_req_duration_$quantile_stat"
      }
     ]
    },
    {
     "title": "HTTP Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 372 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
       "legendFormat": "http_req_s"
      },
      {
       "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval]))",
       "legendFormat": "http_req_s_errors"
      },
      {
       "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"true\"}[$__rate_interval]))",
       "legendFormat": "http_req_s_success"
      }
     ]
    }
   ]
  },
  {
   "title": "Checks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error log $transaction",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
     "repeat": "transaction",
     "targets": [
      {
       "direction": "backward",
       "expr": "{job=\"k6\"}\n| json\n| api=~\"$API\"\n| line_format \"api: {{.api}}\\nurl: {{.url}}\\nstatus: {{.status}}\\n\\nheader: {{.body}}\""
      }
     ]
    }
   ]
  },
  { "title": "Run Result", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Execution detail (Transaction)",
   "type": "table",
   "description": "min/max/p95/p99 depends on the available Quantile Stats",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "avg by (transaction) (k6_trx_duration_pass_min{testid=~\"$testid\"})/1000",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (transaction) (k6_trx_duration_pass_max{testid=~\"$testid\"})/1000",
     "legendFormat": "max"
    },
    {
     "expr": "avg by (transaction) (k6_trx_duration_pass_avg{testid=~\"$testid\"})/1000",
     "legendFormat": "p95"
    },
    {
     "expr": "avg by (transaction) (k6_trx_duration_pass_p90{testid=~\"$testid\"})/1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_trx_count_fail_total{testid=~\"$testid\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_trx_count_pass_total{testid=~\"$testid\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_trx_count_total{testid=~\"$testid\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(k6_trx_count_pass_fail{testid=~\"$testid\"}/k6_trx_count_pass_total{testid=~\"$testid\"})*k6_trx_count_total{testid=~\"$testid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution detail (Api)",
   "type": "table",
   "description": "min/max/p95/p99 depends on the available Quantile Stats",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "avg by(name, status,api,transaction) (k6_http_req_duration_min{testid=~\"$testid\",name!=\"http://10.243.208.74:3100/loki/api/v1/push\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg by(name, status,transaction) (k6_http_req_duration_max{testid=~\"$testid\",name!=\"http://10.243.208.74:3100/loki/api/v1/push\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg by(name, status,transaction) (k6_http_req_duration_avg{testid=~\"$testid\",name!=\"http://10.243.208.74:3100/loki/api/v1/push\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "avg by(name, status,transaction) (k6_http_req_duration_p90{testid=~\"$testid\",name!=\"http://10.243.208.74:3100/loki/api/v1/push\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_reqs_total{testid=~\"$testid\",expected_response=\"false\",name!=\"http://10.243.208.74:3100/loki/api/v1/push\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_reqs_total{testid=~\"$testid\",expected_response=\"true\",name!=\"http://10.243.208.74:3100/loki/api/v1/push\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_reqs_total{testid=~\"$testid\",name!=\"http://10.243.208.74:3100/loki/api/v1/push\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(k6_http_reqs_total{testid=~\"$testid\",expected_response=\"false\",name!=\"http://10.243.208.74:3100/loki/api/v1/push\"}/k6_http_reqs_total{testid=~\"$testid\",expected_response=\"true\",name!=\"http://10.243.208.74:3100/loki/api/v1/push\"})*k6_http_reqs_total{testid=~\"$testid\",name!=\"http://10.243.208.74:3100/loki/api/v1/push\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true
  }
 ]
}